### ISSUE TITLE
Server crashes when trying to execute select * from plpgsql_check_function('fx()');

### ISSUE THREAD

**Issue by nkPit** [okbob/plpgsql_check#172]
Hello! 

When attempting to execute the following request:

```sql 
create table public.testt(a int, b int);

create or replace function fx()
returns void as $$
declare
  v1 varchar default 'public';
  v2 varchar default 'testt';
  v3 varchar default 'x';
begin
  raise notice '%', format('%I.%I.%I', v1, v2, v3);
  perform 'pragma:assert-column:= v1, v2, v3';
end;
$$ language plpgsql;

select * from plpgsql_check_function('fx()');

drop function fx();
```

the server crashes. 

coredump:

```bash
#0  0x00007fd9687189fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fd9687189fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fd9686c4476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fd9686aa7f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000055abcda13c22 in __sanitizer::Abort() ()
#4  0x000055abcda1f7dc in __sanitizer::Die() ()
#5  0x000055abcd9fec8c in __asan::ScopedInErrorReport::~ScopedInErrorReport() ()
#6  0x000055abcd9fc6d4 in __asan::ReportDeadlySignal(__sanitizer::SignalContext const&) ()
#7  0x000055abcd9fb962 in __asan::AsanOnDeadlySignal(int, void*, void*) ()
#8  <signal handler called>
#9  0x00007fd95a1c6a41 in check_var_column (cstate=cstate@entry=0x7ffdc749f310, dno1=160, dno2=0,
    dno3=<optimized out>) at src/parser.c:940
#10 0x00007fd95a1cbafc in plpgsql_check_pragma_assert (cstate=cstate@entry=0x7ffdc749f310,
    pat=pat@entry=PLPGSQL_CHECK_PRAGMA_ASSERT_COLUMN, str=str@entry=0x61900003d4fd "= v1, v2, v3",
    ns=ns@entry=0x6290000450a0, lineno=lineno@entry=8) at src/parser.c:1070
#11 0x00007fd95a1dc133 in pragma_apply (cstate=cstate@entry=0x7ffdc749f310, pv=pv@entry=0x7ffdc749f3bc,
    pragma_str=pragma_str@entry=0x61900003d4ef "assert-column:= v1, v2, v3", ns=0x6290000450a0, lineno=8)
    at src/pragma.c:206
#12 0x00007fd95a1dc91f in plpgsql_check_pragma_apply (cstate=cstate@entry=0x7ffdc749f310,
    pragma_str=pragma_str@entry=0x61900003d4ef "assert-column:= v1, v2, v3", ns=<optimized out>,
    lineno=<optimized out>) at src/pragma.c:263
#13 0x00007fd95a1a64ba in ExprGetQuery (cstate=cstate@entry=0x7ffdc749f310, expr=expr@entry=0x629000046430,
    plansource=<optimized out>) at src/check_expr.c:490
#14 0x00007fd95a1a72ed in prepare_plan (cstate=cstate@entry=0x7ffdc749f310, expr=expr@entry=0x629000046430,
    cursorOptions=cursorOptions@entry=0, parser_setup=parser_setup@entry=0x0, arg=arg@entry=0x0)
    at src/check_expr.c:299
#15 0x00007fd95a1ac9c2 in plpgsql_check_expr_as_sqlstmt (cstate=cstate@entry=0x7ffdc749f310,
    expr=<optimized out>) at src/check_expr.c:1636
#16 0x00007fd95a1f63fa in plpgsql_check_stmt (cstate=cstate@entry=0x7ffdc749f310, stmt=stmt@entry=0x629000046400, closing=closing@entry=0x7ffdc749e900, exceptions=exceptions@entry=0x7ffdc749e910) at src/stmtwalk.c:733
#17 0x00007fd95a1fa3cf in check_stmts (cstate=cstate@entry=0x7ffdc749f310, stmts=<optimized out>, closing=closing@entry=0x7ffdc749ef60, exceptions=exceptions@entry=0x7ffdc749ef70) at src/stmtwalk.c:1355
#18 0x00007fd95a1f247f in plpgsql_check_stmt (cstate=cstate@entry=0x7ffdc749f310, stmt=<optimized out>, closing=closing@entry=0x7ffdc749ef60, exceptions=exceptions@entry=0x7ffdc749ef70) at src/stmtwalk.c:258
#19 0x00007fd95a1b1897 in function_check (func=0x629000020998, cstate=cstate@entry=0x7ffdc749f310) at src/check_function.c:541
#20 0x00007fd95a1b3ecd in plpgsql_check_function_internal (ri=ri@entry=0x7ffdc749f710, cinfo=cinfo@entry=0x7ffdc749f760) at src/check_function.c:227
#21 0x00007fd95a1fcf54 in check_function_internal (fnoid=<optimized out>, fcinfo=fcinfo@entry=0x62500007fa18) at src/tablefunc.c:219
#22 0x00007fd95a1ffd64 in plpgsql_check_function_name (fcinfo=0x62500007fa18) at src/tablefunc.c:605
#23 0x000055abce2195b8 in ExecMakeTableFunctionResult (setexpr=0x62500005a780, econtext=0x62500005a650, argContext=<optimized out>, expectedDesc=<optimized out>, randomAccess=<optimized out>) at execSRF.c:235
#24 0x000055abce27125d in FunctionNext (node=0x62500005a440) at nodeFunctionscan.c:95
#25 0x000055abce21c461 in ExecScanFetch (node=node@entry=0x62500005a440, accessMtd=accessMtd@entry=0x55abce270e6d <FunctionNext>, recheckMtd=recheckMtd@entry=0x55abce270dc4 <FunctionRecheck>) at execScan.c:132
#26 0x000055abce21c6ac in ExecScan (node=0x62500005a440, accessMtd=accessMtd@entry=0x55abce270e6d <FunctionNext>, recheckMtd=recheckMtd@entry=0x55abce270dc4 <FunctionRecheck>) at execScan.c:181
#27 0x000055abce270e28 in ExecFunctionScan (pstate=<optimized out>) at nodeFunctionscan.c:270
#28 0x000055abce21104f in ExecProcNodeFirst (node=0x62500005a440) at execProcnode.c:464
#29 0x000055abce1ef146 in ExecProcNode (node=0x62500005a440) at ../../../src/include/executor/executor.h:273
#30 ExecutePlan (estate=estate@entry=0x62500005a218, planstate=0x62500005a440, use_parallel_mode=<optimized out>, use_parallel_mode@entry=false, operation=operation@entry=CMD_SELECT, sendTuples=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x625000006cc0, execute_once=true) at execMain.c:1670
#31 0x000055abce1ef747 in standard_ExecutorRun (queryDesc=0x61900002db98, direction=ForwardScanDirection, count=0, execute_once=execute_once@entry=true) at execMain.c:365
#32 0x000055abce1ef9ab in ExecutorRun (queryDesc=queryDesc@entry=0x61900002db98, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) at execMain.c:309
#33 0x000055abce985d95 in PortalRunSelect (portal=portal@entry=0x625000025a18, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x625000006cc0) at pquery.c:924
#34 0x000055abce98c02c in PortalRun (portal=portal@entry=0x625000025a18, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x625000006cc0, altdest=altdest@entry=0x625000006cc0, qc=<optimized out>) at pquery.c:768
#35 0x000055abce97fd70 in exec_simple_query (query_string=query_string@entry=0x625000005218 "select * from plpgsql_check_function('fx()');") at postgres.c:1274
#36 0x000055abce984b87 in PostgresMain (dbname=dbname@entry=0x6250000020e8 "postgres", username=username@entry=0x62900001b358 "test") at postgres.c:4637
#37 0x000055abce72385d in BackendRun (port=port@entry=0x614000001240) at postmaster.c:4464
#38 0x000055abce72bfe6 in BackendStartup (port=port@entry=0x614000001240) at postmaster.c:4192
#39 0x000055abce72c5e3 in ServerLoop () at postmaster.c:1782
#40 0x000055abce72ec0e in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x603000000400) at postmaster.c:1466
#41 0x000055abce37f054 in main (argc=3, argv=0x603000000400) at main.c:198
```

Postgres version:

```
postgres=# select version();
                                                version
-------------------------------------------------------------------------------------------------------
 PostgreSQL 16.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
```

plpgsql_check version: 

```sql
plpgsql_check | 2.7     | public     | extended check for plpgsql functions
```
commit: `85d60d3285fb036df68fc2007e2b2f36845a6a08`

Best regards,
Nikita Kalinin
Postgres Professional: http://postgrespro.com/

**Comment by okbob** [comment]
should be fixed in 2.7.6

**Comment by nkPit** [comment]
Yes. The bug is gone. Thanks for fixing it.

**Comment by okbob** [comment]
Thank you for bug report
